volumes:
  database:
    driver: local

services:
  postgres-db:
    image: postgres:12.19
    platform: linux/amd64
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: library_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
